# Author : Anthony Geay (EDF R&D)

IF(OTGUI_ROOT_DIR)
  LIST(APPEND CMAKE_PREFIX_PATH "${OTGUI_ROOT_DIR}")
ENDIF(OTGUI_ROOT_DIR)

FIND_LIBRARY(OTGUI_otguiview otguiview)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OTGUI REQUIRED_VARS OTGUI_otguiview)
